### PR TITLE
Helm version fixes

### LINKED ISSUE #51: Enhancement: remove the need for HELM_VERSION env variable for docker deployments
It should automatically use the "tool" version of helm

### PR DESCRIPTION
**Pull request by bartlettc22**
Fixes #51

### CODE REVIEW

File: stimpacks/deploy/docker.go [hunk 1]
```diff
@@ -32,9 +33,27 @@ func (d *Deploy) startDeployContainer(instance *Instance) {
...
+			deprecatedHelmVersionSet = true
+		}
+		envs = append(envs, fmt.Sprintf("%s=%s", e.Name, e.Value))
+	}
+
+	if _, ok := instance.Spec.Tools["helm"]; ok {
+		if !deprecatedHelmVersionSet {
+			envs = append(envs, fmt.Sprintf("HELM_VERSION=%s", downloader.GetBaseVersion(instance.Spec.Tools["helm"].Version)))
+		} else {
+			d.log.Warn("Both `spec.tools.helm` and the deprecated HELM_VERSION environment variable are set.  HELM_VERSION is taking precedence")
```
Comment (lwahlmeier) [inline stimpacks/deploy/docker.go]: Might log the actual version we ended up using here too just so they know.

**Review by lwahlmeier — APPROVED** [review]

File: stimpacks/deploy/docker.go (hunk 1 above)
Comment (bartlettc22) [reply stimpacks/deploy/docker.go]: fixed

**Review by thorix — APPROVED** [review]
Looks good after testing!
